### ISSUE TITLE
Is this still being actively developed?

### ISSUE THREAD

**Issue by JacobDB** [miraiakagawa/droptunes#1]
I just remembered the awesome site droptun.es, and was dismayed to find it no longer works. This looks like it might be that project, or at least be inspired by it, but this doesn't seem to be actively developed. Are there any plans to continue developing this project?

**Comment by miraiakagawa** [comment]
This project has nothing to do with the droptun.es site, and unfortunately have no plans to be maintained further.

Thanks for reaching out,
Mirai
